name: Run Scraper on Links Update

on:
  push:
    paths:
      - links.py  # Trigger only when links.py changes

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9  # Adjust to your Python version if needed

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 requests pandas openpyxl

    - name: Run Scraper
      run: python scrapper.py

    - name: Commit and Push Results
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "<your-email>@users.noreply.github.com"
        git add *.xlsx
        git commit -m "Updated scraped data based on links.py change"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
